routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/rules', 'HomeController@rules')->name('rules');

Route::resource('links', 'LinkController', ['only' => ['index', 'store', 'show', 'destroy']]);
Route::get('links/prolong/{link}', 'LinkController@prolong')->name('links.prolong');
Route::post('links/disable/{link}', 'LinkController@disable')->name('links.disable');

Route::resource('feedback', 'FeedbackController', ['only' => ['create', 'store']]);

Route::group(
    [
        'prefix' => 'admin',
        'namespace' => 'Admin',
        'as' => 'admin.',
        'middleware' => ['auth', 'can:admin-role']
    ],
    function() {
        Route::get('/', 'HomeController@index')->name('index');
        Route::resource('domains', 'DomainController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('banned-domains', 'BannedDomainController', ['except' => ['show']]);
        Route::resource('users', 'UserController', ['only' => ['index', 'show']]);
        Route::post('users/{user}/premium-add', 'UserController@premiumAdd')->name('users.premium-add');
        Route::resource('feedback', 'FeedbackController', ['only' => ['index', 'show', 'destroy']]);
    }
);

Route::get('/api', function() { abort(404); });
Route::get('/news', function() { abort(404); });
Route::get('/blog', function() { abort(404); });
Route::get('/articles', function() { abort(404); });

Route::get('/{key}', 'RedirectController@redirect')->name('redirect');

app/Http/Controllers/Admin/HomeController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function index()
    {
        $metaData = ['title' => __('Администрирование')];

        return view('admin.home.index', [
            'META_DATA' => $metaData,
            'BREADCRUMBS' => [
                env('APP_NAME') => route('home'),
            ]
        ]);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    // icomment

    // бан листы

    // страница "сокрашенные / короткие ссылки со статистикой" - подробное инфо о ссылках с скринами графиков и прочего

    // для премиума в отчеты по ссылкам можно добавить не только период, а выбор страны, города, девайс тайпа, браузера - сто даст смотреть более детальные отчеты

    // добавить покупку-пробник - 3 дня премиума - покупка доступна только один раз

    // индикатор/статус бар аккаунта (туда как раз убрать индикацию имени)

    // icomment - слерд релиз
    // нормальный диалог о удалении
    // подключение платежых апи

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $metaData = [
            'title' => 'Сократить ссылку',
            'description' => 'LetsGo - сервис, который поможет сократить ссылку, собрать статистику переходов по сокращенной ссылке, а так же задать свой собственный короткий путь. Сервис позволяет создавать ссылки с условно вечной активностью.',
            'keywords' => 'сократить ссылку, ссылка сокращение, сокращенная ссылка',
        ];

        return view('home.index', [
            'META_DATA' => $metaData,
        ]);
    }

    public function about()
    {
        $metaData = [
            'title' => 'Короткая ссылка',
            'description' => 'Короткая ссылка - важнейший инструмент в современном мире и сервис LetsGo поможет сделать такую ссылку. Информация о различных вариантах использования и доступном функционале сервиса коротких ссылок на этой странице.',
            'keywords' => 'короткая ссылка',
        ];

        return view('home.about', [
            'META_DATA' => $metaData,
        ]);
    }

    public function rules()
    {
        $metaData = ['title' => __('Правила и условия пользования сервисом')];

        return view('home.rules', [
            'META_DATA' => $metaData,
        ]);
    }
}

resources/views/admin/home/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>{{ $META_DATA['title'] }}</h1>

        <div class="row">
            <div class="col-md-8 col-sm-12">
            </div>

            <div class="col-md-4 col-sm-12">
                <div class="card">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <a href="{{ route('admin.users.index') }}">{{ __('Пользователи') }}</a>
                        </li>
                        <li class="list-group-item">
                            @php
                                $newFeedbackCount = \App\Helpers\UserHelper::newFeedbackCount(Auth::user());
                            @endphp
                            <a href="{{ route('admin.feedback.index') }}">{{ __('Обратная связь') }}
                                {!! ($newFeedbackCount ? '(<b>'.$newFeedbackCount.'</b>)' : '') !!}</a>
                        </li>
                        <li class="list-group-item">
                            <a href="{{ route('admin.domains.index') }}">{{ __('Домены') }}</a>
                        </li>
                        <li class="list-group-item">
                            <a href="{{ route('admin.banned-domains.index') }}">{{ __('Запрещенные домены') }}</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection