routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/rules', 'HomeController@rules')->name('rules');

Route::resource('links', 'LinkController', ['only' => ['index', 'store', 'show', 'destroy']]);
Route::get('links/prolong/{link}', 'LinkController@prolong')->name('links.prolong');
Route::post('links/disable/{link}', 'LinkController@disable')->name('links.disable');

Route::resource('feedback', 'FeedbackController', ['only' => ['create', 'store']]);

Route::group(
    [
        'prefix' => 'admin',
        'namespace' => 'Admin',
        'as' => 'admin.',
        'middleware' => ['auth', 'can:admin-role']
    ],
    function() {
        Route::get('/', 'HomeController@index')->name('index');
        Route::resource('domains', 'DomainController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('banned-domains', 'BannedDomainController', ['except' => ['show']]);
        Route::resource('users', 'UserController', ['only' => ['index', 'show']]);
        Route::post('users/{user}/premium-add', 'UserController@premiumAdd')->name('users.premium-add');
        Route::resource('feedback', 'FeedbackController', ['only' => ['index', 'show', 'destroy']]);
    }
);

Route::get('/api', function() { abort(404); });
Route::get('/news', function() { abort(404); });
Route::get('/blog', function() { abort(404); });
Route::get('/articles', function() { abort(404); });

Route::get('/{key}', 'RedirectController@redirect')->name('redirect');

app/Models/Link.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
    protected $fillable = [
        'status',
        'user_id',
        'target',
        'expires_at',
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function domain()
    {
        return $this->belongsTo('App\Models\Domain');
    }

    public function inProlongPeriod()
    {
        return date('Ymd', time() + (24 * 60 * 60 * (int)config('common.link_prolong_period')))
            >= date('Ymd', strtotime($this->expires_at));
    }
}

app/Http/Controllers/LinkController.php
<?php

namespace App\Http\Controllers;

use App\ConstantSets\LinkStatus;
use App\Helpers\LinkHelper;
use App\Http\Requests\LinkFormRequest;
use App\Http\Requests\LinkShowRequest;
use App\Models\Link;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LinkController extends Controller
{
    const SORTING_CREATED = 'created';
    const SORTING_EXPIRES = 'expires';

    public function __construct()
    {
        $this->middleware('auth', ['except' => ['store']]);
    }

    public function index(Request $request)
    {
        // icomment - тут нужен поиск по подстроке в кее и таргете

        $user = Auth::user();
        $links = $user->links();

        if ($sorting = $request->input('sorting')) {
            switch ($sorting) {
                case self::SORTING_EXPIRES:
                    $links = $links->orderBy('expires_at');
                    break;
            }
        }

        $links = $links->orderBy('created_at', 'desc')->paginate(100);

        $metaData = ['title' => __('Мои ссылки')];

        return view('link.index', [
            'links' => $links,
            'linksCount' => $user->links()->count(),
            'sortings' => [
                self::SORTING_CREATED => 'По дате создания',
                self::SORTING_EXPIRES => 'По дате активности',
            ],
            'sorting' => $sorting,
            'isPremium' => Auth::check() && Auth::user()->isPremium(),
            'META_DATA' => $metaData,
            'BREADCRUMBS' => [
                env('APP_NAME') => route('home'),
            ]
        ]);
    }

    public function store(LinkFormRequest $request)
    {
        $currentUser = Auth::user();

        if ($currentUser instanceof User) {

            if ($currentUser->links()->count() >= config('common.user_links_limit')) {
                return redirect()->back()->withErrors(__('Достигнут лимит ссылок для данного аккаунта. Для увеличения лимита свяжитесь с администратором.'));
            }

            $userId = $currentUser->id;
        } else {
            $userId = null;
        }

        $link = new Link();
        $link->fill($request->all());
        $link->user_id = $userId;

        if ($request->filled('key') && $currentUser->isPremium()) {
            $link->key = trim($request->input('key'));
        }

        $lifeTimeDays = LinkHelper::lifeTimeDays($currentUser);
        $link->expires_at = date('Y-m-d H:i:s', time() + ($lifeTimeDays * 24 * 60 * 60));

        if ($link->save()) {
            return redirect()->back()->with('new-link', route('redirect', ['key' => $link->key]));
        } else {
            return redirect()->back()->withErrors('Ошибка сохранения ссылки');
        }
    }

    public function show(LinkShowRequest $request, $key)
    {
        if (!$link = Link::where('key', $key)->where('status', LinkStatus::ENABLED)->first()) {
            abort(404);
        }

        $this->authorize('view', $link);

        $metaData = ['title' => __('Ссылка').': '.$link->key];

        $begin = $request->filled('begin') ? strtotime($request->input('begin')) : time() - 30 * 24 * 60 * 60;
        $end = $request->filled('end') ? strtotime($request->input('end')) : time();

        $isPremium = Auth::check() && Auth::user()->isPremium();

        return view('link.show', [
            'link' => $link,
            'begin' => date('Y-m-d', $begin),
            'end' => date('Y-m-d', $end),
            'isPremium' => $isPremium,
            'shows' => LinkHelper::showsByPeriod($link, $begin, $end),
            'deviceTypes' => $isPremium ? LinkHelper::deviceTypesByPeriod($link, $begin, $end) : [],
            'browsers' => $isPremium ? LinkHelper::browsersByPeriod($link, $begin, $end) : [],
            'countries' => $isPremium ? LinkHelper::countriesByPeriod($link, $begin, $end) : [],
            'cities' => $isPremium ? LinkHelper::citiesByPeriod($link, $begin, $end) : [],
            'META_DATA' => $metaData,
            'BREADCRUMBS' => [
                env('APP_NAME') => route('home'),
                __('Ссылки') => route('links.index'),
            ]
        ]);
    }

    public function prolong(Link $link)
    {
        $this->authorize('prolong', $link);

        $currentUser = Auth::user();
        $lifeTimeDays = LinkHelper::lifeTimeDays($currentUser);
        $link->expires_at = date('Y-m-d H:i:s', strtotime($link->expires_at) + ($lifeTimeDays * 24 * 60 * 60));
        $link->save();

        return [
            'link_id' => $link->id,
            'expires_at' => date('Y-m-d H:i', strtotime($link->expires_at)),
        ];
    }

    public function disable($key)
    {
        if (!$link = Link::where('key', $key)->first()) {
            abort(404);
        }

        $this->authorize('disable', $link);
        $link->status = LinkStatus::DISABLED;
        $link->save();
        return redirect()->back()->with('success', 'Успешно удалено');
    }

    public function destroy($key)
    {
        if (!$link = Link::where('key', $key)->first()) {
            abort(404);
        }

        $this->authorize('delete', $link);
        $link->delete();
        return redirect()->back()->with('success', 'Успешно удалено');
    }
}

resources/views/link/form.blade.php
@if(\Session::has('new-link'))

    <div class="link-view text-center">
        <a href="{{\Session::get('new-link')}}" target="_blank">{{\Session::get('new-link')}}</a>
        <i class="btn btn-link fa fa-copy" copy-to-clipboard="{{\Session::get('new-link')}}" title="{{ __('Скопировать в буфер') }}"></i>
    </div>

    <p class="text-center">

        Срок активности ссылки  <b>{{ LinkHelper::lifeTimeDays() }} дней</b>.

        @if(!Auth::check())
            <a href="{{ route('register') }}">Зарегистрированные</a> пользователи могут создавать ссылки с большим
            сроком активности, более короткой длины, а также видеать статистику переходов по ссылке.
        @elseif(Auth::user()->isPremium())
            Обладатели премиум-аккаунта могут продлевать срок активности ссылки за
            {{ config('common.link_prolong_period') }} дней до его истечения.
        @else
            Обладатели премиум-аккаунта могут продлевать срок активности ссылки за
            {{ config('common.link_prolong_period') }} дней до его истечения,
            а также видеть расширенную статистику ссылок.
        @endif
    </p>

@else

    {{ Form::open(['url' => route('links.store'), 'method' => 'POST']) }}

        @if(Auth::check() && Auth::user()->isPremium())
            @include('link.form_premium')
        @else
            @include('link.form_short')
        @endif

    {{ Form::close() }}

@endif

resources/views/link/form_premium.blade.php
<div class="row">
    <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1 col-sm-12 offset-sm-0">
        <div class="form-group">
            {{ Form::text('target', null, ['class' => 'form-control '.($errors->has('target') ? ' is-invalid' : '' ), 'autocomplete' => 'off']) }}
        </div>

        <div class="form-group text-center" style="display: {{ old('key') ? 'none' : 'block' }};">
            <button type="button" class="btn btn-link" id="show-custom-link-key">Указать желаемый адрес ссылки</button>
        </div>

        <div class="form-group text-center" style="display: {{ old('key') ? 'block' : 'none' }};" id="custom-link-key-wrap">
            <label>Желаемый короткий адрес:</label>
            {{ Form::text('key', null, ['class' => 'form-control '.($errors->has('key') ? ' is-invalid' : '' ), 'autocomplete' => 'off']) }}
        </div>

        <div class="form-group text-center">
            <button type="submit" class="btn btn-primary btn-lg">СОКРАТИТЬ</button>
        </div>
    </div>
</div>

resources/views/link/form_short.blade.php
<div class="row">
    <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1 col-sm-12 offset-sm-0">
        <div class="form-group">
            {{ Form::text('target', null, ['class' => 'form-control '.($errors->has('target') ? ' is-invalid' : '' ), 'autocomplete' => 'off']) }}
        </div>
        <div class="form-group text-center">
            <button type="submit" class="btn btn-primary btn-lg">Сократить</button>
        </div>
    </div>
</div>

resources/views/link/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>{{ $META_DATA['title'] }}</h1>

        @include('link.form')

        <div class="alert {{ ($linksCount * 100 / config('common.user_links_limit')) > 90 ? 'alert-danger' : 'text-dark alert-secondary' }}">
            <small>
                {{ __('Количество активных ссылок') }}: {{ $linksCount }}.
                {{ __('Лимит активных ссылок') }}: {{ config('common.user_links_limit') }}.
                {{ __('В случае необходимости увеличения лимита ссылок свяжитесь с администратором') }}.
            </small>
        </div>

        @include('link.table')

    </div>
@endsection

resources/views/link/item.blade.php
<div class="row {{ $link->inProlongPeriod() ? 'bg-warning' : '' }}">
    <div class="col-md-8 col-sm-12">
        <p class="mb-0"><a href="{{ route('links.show', $link->key) }}">{{ $link->key }}</a></p>
        <small>{{ $link->target }}</small>
    </div>
    <div class="col-md-2 col-sm-12" link-prolong-value="{{ $link->id }}">
        {{ date('Y-m-d H:i', strtotime($link->expires_at)) }}
        @if($link->inProlongPeriod())
            <p class="mb-0">
                @if($isPremium)
                    <span class="btn btn-link p-0" link-prolong path="{{ route('links.prolong', $link->id) }}">
                        {{ __('Продлить') }}
                    </span>
                @else
                    <a href="{{ route('about', ['#premium']) }}" target="_blank">
                        {{ __('Продлить') }}
                    </a>
                @endif
            </p>
        @endif
    </div>
    <div class="col-md-2 col-sm-12 text-right">

        <i class="btn btn-link fa fa-copy p-0 pl-2" copy-to-clipboard="{{ route('redirect', $link->key) }}" title="{{ __('Скопировать в буфер') }}"></i>

        <a href="{{ route('redirect', $link->key) }}" target="_blank" class="btn btn-light text-primary fa fa-external-link p-0 pl-2" title="{{ __('Перейти') }}"></a>

        <a href="{{ route('links.show', $link->key) }}" target="_blank" class="btn btn-light text-primary fa fa-edit p-0 pl-2" title="{{ __('Редактировать') }}"></a>

        {{ Form::model($link, ['url' => route('links.disable', ['link' => $link->key, '_method' => 'POST']), 'delete-form' => '1']) }}
        <button type="submit" class="btn btn-light text-danger fa fa-times p-0 pl-2" title="{{ __('Удалить') }}"></button>
        {{ Form::close() }}
    </div>
</div>

resources/views/link/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>{{ $META_DATA['title'] }}</h1>

        <div class="row mb-3">
            <div class="col-md-4 col-sm-12">
                <a href="{{ route('redirect', $link->key) }}" target="_blank">
                    {{ route('redirect', $link->key) }}
                </a>
                <i class="btn btn-link fa fa-copy" copy-to-clipboard="{{ route('redirect', $link->key) }}" title="{{ __('Скопировать в буфер') }}"></i>
            </div>
            <div class="col-md-4 col-sm-12">
                {{ __('Создана') }}: {{ date('Y-m-d H:i', strtotime($link->created_at)) }}
            </div>
            <div class="col-md-4 col-sm-12">
                {{ __('Активна до') }}: {{ date('Y-m-d H:i', strtotime($link->expires_at)) }}
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-12">
                <div class="card">
                    <div class="card-body pb-1">
                        <div class="card-title">
                            <h3>{{ __('Настройки') }}</h3>
                        </div>
                        <form method="get">
                            <div class="row">
                                <div class="col-md-4 col-sm-12 form-group">
                                    <p class="mb-1">{{ __('Начало периода') }}:</p>
                                    {{ Form::text('begin', (isset($begin) ? $begin : old('begin')), [
                                        'class' => 'form-control datepicker',
                                        'placeholder' => 'ГГГГ-ММ-ДД',
                                        'mask-date' => 1,
                                        'autocomplete' => 'off',
                                    ]) }}
                                </div>
                                <div class="col-md-4 col-sm-12 form-group">
                                    <p class="mb-1">{{ __('Конец периода') }}:</p>
                                    {{ Form::text('end', (isset($end) ? $end : old('end')), [
                                        'class' => 'form-control datepicker',
                                        'placeholder' => 'ГГГГ-ММ-ДД',
                                        'mask-date' => 1,
                                        'autocomplete' => 'off',
                                    ]) }}
                                </div>
                                <div class="col-md-4 col-sm-12 form-group">
                                    <p class="hide-on-mobile mb-1">&nbsp;</p>
                                    <button type="submit" class="btn btn-primary">{{ __('Показать') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <h3>{{ __('Количество переходов') }}</h3>
                        </div>
                        @if($shows)
                            <canvas
                                    id="link-visits-chart"
                                    chart-js-line
                                    axis-x="{{ implode(';', array_keys($shows)) }}"
                                    axis-y="{{ implode(';', $shows) }}"
                            ></canvas>
                        @else
                            <p class="text-center text-black-50">
                                {{ __('Нет данных') }}
                            </p>
                        @endif
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-sm-12 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <h3>{{ __('Тип устройства') }}</h3>

                            @if(!$isPremium)
                                <div class="text-center">
                                    <a href="{{ route('about', ['#premium']) }}" target="_blank">
                                        <i class="fa fa-lock fa-2x"></i>
                                    </a>
                                </div>
                            @elseif($deviceTypes)
                                <canvas
                                        id="link-device-type-chart"
                                        chart-js-doughnut
                                        axis-x="{{ implode(';', array_keys($deviceTypes)) }}"
                                        axis-y="{{ implode(';', $deviceTypes) }}"
                                ></canvas>
                            @else
                                <p class="text-center text-black-50">
                                    {{ __('Нет данных') }}
                                </p>
                            @endif

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-12 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <h3>{{ __('Браузер') }}</h3>

                            @if(!$isPremium)
                                <div class="text-center">
                                    <a href="{{ route('about', ['#premium']) }}" target="_blank">
                                        <i class="fa fa-lock fa-2x"></i>
                                    </a>
                                </div>
                            @elseif($browsers)
                                <canvas
                                        id="link-browser-chart"
                                        chart-js-doughnut
                                        axis-x="{{ implode(';', array_keys($browsers)) }}"
                                        axis-y="{{ implode(';', $browsers) }}"
                                ></canvas>
                            @else
                                <p class="text-center text-black-50">
                                    {{ __('Нет данных') }}
                                </p>
                            @endif

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-12 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <h3>{{ __('Страна') }}</h3>

                            @if(!$isPremium)
                                <div class="text-center">
                                    <a href="{{ route('about', ['#premium']) }}" target="_blank">
                                        <i class="fa fa-lock fa-2x"></i>
                                    </a>
                                </div>
                            @elseif($countries)
                                <canvas
                                        id="link-country-chart"
                                        chart-js-doughnut
                                        axis-x="{{ implode(';', array_keys($countries)) }}"
                                        axis-y="{{ implode(';', $countries) }}"
                                ></canvas>
                            @else
                                <p class="text-center text-black-50">
                                    {{ __('Нет данных') }}
                                </p>
                            @endif

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-12 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <h3>{{ __('Город') }}</h3>

                            @if(!$isPremium)
                                <div class="text-center">
                                    <a href="{{ route('about', ['#premium']) }}" target="_blank">
                                        <i class="fa fa-lock fa-2x"></i>
                                    </a>
                                </div>
                            @elseif($cities)
                                <canvas
                                        id="link-city-chart"
                                        chart-js-doughnut
                                        axis-x="{{ implode(';', array_keys($cities)) }}"
                                        axis-y="{{ implode(';', $cities) }}"
                                ></canvas>
                            @else
                                <p class="text-center text-black-50">
                                    {{ __('Нет данных') }}
                                </p>
                            @endif

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/link/table.blade.php
<div class="row">
    <div class="col-md-9 col-sm-12">
        {{ $links->appends($_GET)->links('common.pagination') }}
    </div>
    <div class="col-md-3 col-sm-12">
        <div class="form-group">

            {{ Form::open([
                'id' => 'sorting-form',
                'method' => 'GET',
                'url' => route('links.index'),
            ]) }}

            {{ Form::select('sorting', $sortings, $sorting, [
            'class' => 'form-control',
             'sorting-field' => '1',
             'form' => 'sorting-form',
            ]) }}

            {{ Form::close() }}

        </div>
    </div>
</div>

<div class="grid-table">

    <div class="row head bg-dark text-white">
        <div class="col-md-8 col-sm-12">
            Ссылка
        </div>
        <div class="col-md-2 col-sm-12">
            Активна до
        </div>
        <div class="col-md-2 col-sm-12">
            Действия
        </div>
    </div>

    @forelse($links as $link)
        @include('link.item')
    @empty
        <div class="row">
            <div class="col-12 text-center">
                {{ __('Ссылки отсутствуют') }}
            </div>
        </div>
    @endforelse

</div>