routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/rules', 'HomeController@rules')->name('rules');

Route::resource('links', 'LinkController', ['only' => ['index', 'store', 'show', 'destroy']]);
Route::get('links/prolong/{link}', 'LinkController@prolong')->name('links.prolong');
Route::post('links/disable/{link}', 'LinkController@disable')->name('links.disable');

Route::resource('feedback', 'FeedbackController', ['only' => ['create', 'store']]);

Route::group(
    [
        'prefix' => 'admin',
        'namespace' => 'Admin',
        'as' => 'admin.',
        'middleware' => ['auth', 'can:admin-role']
    ],
    function() {
        Route::get('/', 'HomeController@index')->name('index');
        Route::resource('domains', 'DomainController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('banned-domains', 'BannedDomainController', ['except' => ['show']]);
        Route::resource('users', 'UserController', ['only' => ['index', 'show']]);
        Route::post('users/{user}/premium-add', 'UserController@premiumAdd')->name('users.premium-add');
        Route::resource('feedback', 'FeedbackController', ['only' => ['index', 'show', 'destroy']]);
    }
);

Route::get('/api', function() { abort(404); });
Route::get('/news', function() { abort(404); });
Route::get('/blog', function() { abort(404); });
Route::get('/articles', function() { abort(404); });

Route::get('/{key}', 'RedirectController@redirect')->name('redirect');

app/Models/BannedDomain.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BannedDomain extends Model
{
    protected $fillable = [
        'host',
    ];
}

app/Http/Controllers/Admin/BannedDomainController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\BannedDomainFormReqest;
use App\Models\BannedDomain;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BannedDomainController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bannedDomains = BannedDomain::orderBy('host')->paginate(100);

        $metaData = ['title' => 'Запрещенные домены'];

        return view('admin.banned_domain.index', [
            'bannedDomains' => $bannedDomains,
            'META_DATA' => $metaData,
            'BREADCRUMBS' => [
                env('APP_NAME') => route('home'),
                __('Администрирование') => route('admin.index'),
            ]
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $bannedDomain = new BannedDomain();
        return $this->edit($bannedDomain);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BannedDomainFormReqest $request)
    {
        $bannedDomain = new BannedDomain();
        return $this->update($request, $bannedDomain);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\BannedDomain  $bannedDomain
     * @return \Illuminate\Http\Response
     */
    public function edit(BannedDomain $bannedDomain)
    {
        $metaData = ['title' => 'Заблокированные домены: '.($bannedDomain->id ? $bannedDomain->host : 'новый')];

        return view('admin.banned_domain.edit', [
            'bannedDomain' => $bannedDomain,
            'META_DATA' => $metaData,
            'BREADCRUMBS' => [
                env('APP_NAME') => route('home'),
                'Заблокированные домены' => route('admin.banned-domains.index'),
            ]
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\BannedDomain  $bannedDomain
     * @return \Illuminate\Http\Response
     */
    public function update(BannedDomainFormReqest $request, BannedDomain $bannedDomain)
    {
        $bannedDomain->fill($request->all());
        $bannedDomain->save();
        return redirect()
            ->route('admin.banned-domains.edit', $bannedDomain->id)
            ->with('success', 'Успешно сохранено');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\BannedDomain  $bannedDomain
     * @return \Illuminate\Http\Response
     */
    public function destroy(BannedDomain $bannedDomain)
    {
        $bannedDomain->delete();
        return redirect()
            ->route('admin.banned-domains.index')
            ->with('success', 'Успешно удалено');
    }
}

resources/views/admin/banned_domain/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>{{ $META_DATA['title'] }}</h1>

        @if($bannedDomain->id)
            {{ Form::model($bannedDomain, ['url' => route('admin.banned-domains.update', ['banned_domain' => $bannedDomain->id, '_method' => 'PATCH'])]) }}
        @else
            {{ Form::open(['url' => route('admin.banned-domains.store')]) }}
        @endif

        <div class="form-group">
            <label>Host:</label>
            {{ Form::text('host', null, ['class' => 'form-control'.($errors->has('host') ? ' is-invalid' : ''), 'autocomplete' => 'off']) }}
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>

        {{ Form::close() }}

    </div>
@endsection

resources/views/admin/banned_domain/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>{{ $META_DATA['title'] }}</h1>

        <p>
            <a class="btn btn-primary" href="{{ route('admin.banned-domains.create') }}">
                <span class="fa fa-plus"></span> Создать
            </a>
        </p>

        <table class="table" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>Host</th>
                <th></th>
            </tr>
            </thead>

            <tbody>
            @foreach($bannedDomains as $bannedDomain)
                <tr>
                    <td>
                        <a href="{{ route('admin.banned-domains.edit', ['banned_domain' => $bannedDomain->id]) }}">
                            {{ $bannedDomain->host }}
                        </a>
                    </td>
                    <td>
                        {{ Form::model($bannedDomain, ['url' => route('admin.banned-domains.destroy', ['banned_domain' => $bannedDomain->id, '_method' => 'DELETE']), 'delete-form' => '1']) }}
                        <button type="submit" class="btn btn-danger fa fa-trash float-right"></button>
                        {{ Form::close() }}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {{ $bannedDomains->render() }}

    </div>
@endsection