routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/rules', 'HomeController@rules')->name('rules');

Route::resource('links', 'LinkController', ['only' => ['index', 'store', 'show', 'destroy']]);
Route::get('links/prolong/{link}', 'LinkController@prolong')->name('links.prolong');
Route::post('links/disable/{link}', 'LinkController@disable')->name('links.disable');

Route::resource('feedback', 'FeedbackController', ['only' => ['create', 'store']]);

Route::group(
    [
        'prefix' => 'admin',
        'namespace' => 'Admin',
        'as' => 'admin.',
        'middleware' => ['auth', 'can:admin-role']
    ],
    function() {
        Route::get('/', 'HomeController@index')->name('index');
        Route::resource('domains', 'DomainController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('banned-domains', 'BannedDomainController', ['except' => ['show']]);
        Route::resource('users', 'UserController', ['only' => ['index', 'show']]);
        Route::post('users/{user}/premium-add', 'UserController@premiumAdd')->name('users.premium-add');
        Route::resource('feedback', 'FeedbackController', ['only' => ['index', 'show', 'destroy']]);
    }
);

Route::get('/api', function() { abort(404); });
Route::get('/news', function() { abort(404); });
Route::get('/blog', function() { abort(404); });
Route::get('/articles', function() { abort(404); });

Route::get('/{key}', 'RedirectController@redirect')->name('redirect');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="canonical" href="{{ Page::canonical() }}"/>
    <link rel="shortcut icon" href="{{ asset('favicon.png') }}" type="image/x-icon">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

@include('common.meta_title')
@include('common.meta_description')
@include('common.meta_keywords')

<!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">

    @if(env('APP_ENV') === 'production')
        @include('common.head_includes')
    @endif

</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-custom @yield('header-nav-class', '')">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="fa fa-bars"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav">

                    <li class="nav-item">
                        <span class="nav-link" modal-call path="{{ route('feedback.create') }}">
                            {{ __('Обратная связь') }}
                        </span>
                    </li>

                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">
                                {{ __('Вход') }}
                            </a>
                        </li>
                        <li class="nav-item">
                            @if (Route::has('register'))
                                <a class="nav-link" href="{{ route('register') }}">
                                    {{ __('Регистрация') }}
                                </a>
                            @endif
                        </li>
                    @else

                        @if(Auth::user()->isAdmin())
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('admin.index') }}">
                                    {{ __('A') }}
                                </a>
                            </li>
                        @endif

                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('links.index') }}">
                                {{ __('Мои ссылки') }}
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Выход') }}
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>

                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main>
        @include('common.breadcrumbs')
        @include('common.errors')
        @include('common.success')
        @yield('content')
    </main>

    <div class="modal fade" id="modal-wrap" role="dialog" aria-hidden="true">
    </div>
    <!-- Scripts -->
    <script src="{{ mix('js/app.js') }}" defer></script>

</div>
</body>
</html>

resources/views/layouts/modal.blade.php
<div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">@yield('title')</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="alert alert-danger" style="display: none;">
                <ul id="modal-errors">
                </ul>
            </div>
            @yield('body')
        </div>
        <div class="modal-footer">
            @yield('footer')
        </div>
    </div>
</div>